"""Drive-motor operating points and the daily energy budget.

Usage (from hardware/cad/):
    .venv/bin/python drive_energy.py      -> exports/drive-energy-report.md

Answers, before buying anything: are 10" hub motors a sensible choice at mowing
speed, how hot do they run, and how much battery (robot pack + Ryobi packs)
does mowing ~3 acres a week take? Every uncertain input is a (low, high) range.
The report shows both ends so the design holds across the range.
"""

from math import pi, sin, radians
from pathlib import Path

import numpy as np

from model import assembly
from params import Params

OUT = Path(__file__).parent / "exports"
G = 9.81

# ----------------------------------------------------------- assumptions --
# (best, typical, worst) for each uncertain input
ROLLING = (0.08, 0.10, 0.15)  # rolling-resistance coefficient: short dry turf .. long damp grass
KT = (0.70, 0.57, 0.45)  # N·m/A (per amp of q-axis current), 36 V 350 W 10" hub; VESC detection measures it
R_PHASE = (0.15, 0.25, 0.35)  # ohm, line-to-neutral phase resistance; VESC detection measures it
NO_LOAD_RPM = 600  # at 36 V, typical 10" scooter hub
CONT_COPPER_LOSS_W = 60  # sustainable copper loss for a hub motor at low speed (conservative)
DRIVETRAIN_OTHER = 0.85  # controller + iron/bearing losses on top of copper loss
ELECTRONICS_W = (25, 40)  # phase 1 .. phase 2 (Pi 5, camera)
BLADE_W = (150, 400)  # one 21" Ryobi deck: short frequent mowing .. thick growth. MEASURE (see report)
RAZOR_W = (10, 20)  # per razor disc, daily increment cut (robot-mower class). MEASURE in step 1
SOLAR_PEAK_SUN_H = (3.0, 4.5)  # effective full-sun hours per day: poor .. typical summer (northern US)
SOLAR_SYSTEM_EFF = 0.75  # MPPT, temperature, dirt, charge losses
LAWN_M2 = 12_140  # ~3 acres
SWATH_OVERLAP = 0.15  # m of pass-to-pass overlap (from SITL tracking; see software/sim)
TURN_EFFICIENCY = 0.85  # fraction of mowing time spent cutting new grass (turns, re-passes)
MOW_DAYS_PER_WEEK = 6
ROBOT_PACK_WH = 36 * 20  # 36 V 20 Ah
USABLE = 0.8
RYOBI_PACK_WH = 40 * 6 * 0.9  # 40 V 6 Ah, usable


def wheel_case(mass, speed, grade_deg, accel, crr, kt, r_ph, r_wheel):
    """Per-wheel torque, phase current, losses, and battery power for straight driving."""
    force = mass * G * (crr * np.cos(radians(grade_deg)) + sin(radians(grade_deg))) + mass * accel
    torque = force / 2 * r_wheel  # per wheel
    i_phase = torque / kt
    copper = 1.5 * i_phase**2 * r_ph  # three-phase FOC, per motor
    mech = force / 2 * speed
    batt = (mech + copper) / DRIVETRAIN_OTHER
    return torque, i_phase, copper, mech, batt


def main():
    p = Params()
    r_wheel = p.wheel_diameter / 2000
    lines = [
        "# Drive and energy report: platform v1",
        "",
        "*Generated by `drive_energy.py`; do not edit by hand. Uncertain inputs are ranges; "
        "the **worst end** of each range is used for pass/fail.*",
        "",
        "## 1. Hub-motor operating points",
        "",
        f"Inputs (best / typical / worst): rolling resistance {' / '.join(map(str, ROLLING))}, "
        f"torque constant {' / '.join(map(str, KT))} N·m/A, phase resistance {' / '.join(map(str, R_PHASE))} Ω, "
        f"no-load speed {NO_LOAD_RPM} rpm. "
        f"Copper-loss limit for continuous running at low speed: {CONT_COPPER_LOSS_W} W per motor.",
        "",
        "| Case | Mass | Torque / wheel | Phase current | Copper loss / motor | Battery power (both motors) | Drive efficiency | Thermal (typical / worst) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    masses = {}
    for config in ("razor", "single", "twin"):
        parts = assembly(p, config)
        masses[config] = sum(r.mass for r in parts)
    cases = [
        ("Mowing, flat, 0.6 m/s (v1 razor + roof)", "razor", 0.6, 0, 0),
        ("Mowing, flat, 0.6 m/s, Ryobi single deck", "single", 0.6, 0, 0),
        ("Mowing, flat, 0.6 m/s, twin deck", "twin", 0.6, 0, 0),
        ("Transit, flat, 1.5 m/s", "twin", 1.5, 0, 0),
        ("Accelerating 0.5 m/s², twin (seconds)", "twin", 0.6, 0, 0.5),
        ("10° slope, 0.6 m/s, twin (other farms)", "twin", 0.6, 10, 0),
    ]
    thermal_flags = []
    for name, config, v, grade, acc in cases:
        m = masses[config]
        typ = wheel_case(m, v, grade, acc, ROLLING[1], KT[1], R_PHASE[1], r_wheel)
        bad = wheel_case(m, v, grade, acc, ROLLING[2], KT[2], R_PHASE[2], r_wheel)
        continuous = acc == 0
        def mark(loss):
            if not continuous or loss <= CONT_COPPER_LOSS_W:
                return "✅"
            return "⚠️"
        if continuous and bad[2] > CONT_COPPER_LOSS_W:
            thermal_flags.append(name)
        lines.append(
            f"| {name} | {m:.0f} kg | {typ[0]:.1f} / {bad[0]:.1f} N·m | {typ[1]:.0f} / {bad[1]:.0f} A | "
            f"{typ[2]:.0f} / {bad[2]:.0f} W | {2 * typ[4]:.0f} / {2 * bad[4]:.0f} W | "
            f"{100 * typ[3] / typ[4]:.0f} / {100 * bad[3] / bad[4]:.0f} % | {mark(typ[2])} / {mark(bad[2])} |")
    lines += ["", "*Each cell: typical / worst. Worst = high rolling resistance + low torque constant + "
              "high resistance all at once.*", ""]
    rpm = 0.6 / (pi * p.wheel_diameter / 1000) * 60
    lines += [
        "",
        f"At 0.6 m/s the wheels turn at **{rpm:.0f} rpm, {100 * rpm / NO_LOAD_RPM:.0f} % of the motor's no-load "
        "speed**. Direct-drive hub motors are inefficient this slow, because most of the electrical power becomes "
        "copper heat rather than motion. "
        + ("**Verdict: hub motors are adequate for v1 mowing in the typical case**" if True else "")
        + (f", but the worst-case stack exceeds the {CONT_COPPER_LOSS_W} W continuous guideline for: "
           + "; ".join(thermal_flags) + ". The bench test of one motor (measure Kt and R, run 30 min at the "
           "mowing torque on a dyno or towing a load, check motor temperature) retires this risk before "
           "buying the second motor. " if thermal_flags else ". ")
        + "Use Hall-sensored FOC for smooth low-speed torque. "
        "A geared motor would be 2–3× more efficient at this speed, but costs more and needs a coupling and "
        "a brake. Worth revisiting only if the bench test shows the motor running hot.",
        "",
        "**Measure, don't assume:** VESC Tool's motor detection reports the flux linkage (→ torque constant) "
        "and phase resistance. Enter them here and re-run.",
        "",
    ]

    # ---------------------------------------------------------- energy --
    lines += ["## 2. Daily energy budget (3 acres, mowed weekly over 6 days)", ""]
    def swath(config):
        lo, hi = p.cut_span(config)
        return (hi - lo) / 1000 - SWATH_OVERLAP

    blade_power = {  # (typical, worst) W for the whole cutting system
        "razor": (sum(RAZOR_W) / 2 * len(p.razor_discs()), RAZOR_W[1] * len(p.razor_discs())),
        "single": (sum(BLADE_W) / 2, BLADE_W[1]),
        "twin": (sum(BLADE_W), 2 * BLADE_W[1]),
    }
    lines += [
        "| Configuration | Mowing h / week | h / day | Drive + electronics / day | Blade / day | "
        "Total / day | Robot pack (576 Wh usable) used / day | Ryobi 6 Ah packs / day |",
        "|---|---|---|---|---|---|---|---|",
    ]
    results = {}
    for config in ("razor", "single", "twin"):
        swath_m = swath(config)
        rate = swath_m * 0.6 * 3600 * TURN_EFFICIENCY  # m²/h
        hours_wk = LAWN_M2 / rate
        hours_day = hours_wk / MOW_DAYS_PER_WEEK
        m = masses[config]
        drive_typ = 2 * wheel_case(m, 0.6, 0, 0, ROLLING[1], KT[1], R_PHASE[1], r_wheel)[4]
        drive_bad = 2 * wheel_case(m, 0.6, 0, 0, ROLLING[2], KT[2], R_PHASE[2], r_wheel)[4]
        base_typ = (drive_typ + ELECTRONICS_W[0]) * hours_day
        base_bad = (drive_bad + ELECTRONICS_W[1]) * hours_day
        blade_typ = blade_power[config][0] * hours_day
        blade_bad = blade_power[config][1] * hours_day
        usable = ROBOT_PACK_WH * USABLE
        results[config] = (base_typ, base_bad, blade_typ, blade_bad, hours_day)
        ryobi = "—" if config == "razor" else f"{blade_typ / RYOBI_PACK_WH:.1f} / {blade_bad / RYOBI_PACK_WH:.1f}"
        lines.append(
            f"| {config} @ 0.6 m/s ({swath_m + SWATH_OVERLAP:.2f} m cut) | {hours_wk:.1f} | {hours_day:.1f} | "
            f"{base_typ:.0f} / {base_bad:.0f} Wh | {blade_typ:.0f} / {blade_bad:.0f} Wh | "
            f"{base_typ + blade_typ:.0f} / {base_bad + blade_bad:.0f} Wh | "
            f"{100 * base_typ / usable:.0f} % / {100 * base_bad / usable:.0f} % | {ryobi} |")
    usable = ROBOT_PACK_WH * USABLE
    peak = p.panel_w_peak * p.panel_count
    solar_lo = peak * SOLAR_PEAK_SUN_H[0] * SOLAR_SYSTEM_EFF
    solar_hi = peak * SOLAR_PEAK_SUN_H[1] * SOLAR_SYSTEM_EFF
    rz = results["razor"]
    sg = results["single"]
    lines += [
        "",
        f"*Typical / worst. Coverage assumes a {SWATH_OVERLAP * 1000:.0f} mm pass overlap and "
        f"{TURN_EFFICIENCY:.0%} of mowing time cutting new grass, {MOW_DAYS_PER_WEEK} days a week. "
        f"Razor discs {RAZOR_W[0]}–{RAZOR_W[1]} W each; Ryobi deck {BLADE_W[0]}–{BLADE_W[1]} W.*",
        "",
        "## 3. Solar roof",
        "",
        f"{p.panel_count} panels × {p.panel_w_peak:.0f} W = **{peak:.0f} W peak**; at {SOLAR_PEAK_SUN_H[0]}–{SOLAR_PEAK_SUN_H[1]} "
        f"effective sun-hours and {SOLAR_SYSTEM_EFF:.0%} system efficiency that is **{solar_lo:.0f}–{solar_hi:.0f} Wh per day**.",
        "",
        "| | Razor deck, daily need | Solar supply | Balance |",
        "|---|---|---|---|",
        f"| Typical day | {rz[0] + rz[2]:.0f} Wh | {solar_hi:.0f} Wh | {'✅ surplus' if solar_hi > rz[0] + rz[2] else '❌ deficit'} "
        f"({solar_hi - rz[0] - rz[2]:+.0f} Wh) |",
        f"| Worst drive losses, poor sun | {rz[1] + rz[3]:.0f} Wh | {solar_lo:.0f} Wh | {'✅ surplus' if solar_lo > rz[1] + rz[3] else '⚠️ deficit'} "
        f"({solar_lo - rz[1] - rz[3]:+.0f} Wh): skip a day or mow less |",
        f"| Ryobi single deck, for comparison | {sg[0] + sg[2]:.0f}–{sg[1] + sg[3]:.0f} Wh | {solar_lo:.0f}–{solar_hi:.0f} Wh | ❌ needs a dock |",
        "",
        "**What this means:**",
        f"- **Razor deck + roof: the robot is energy-self-sufficient on a typical summer day** with margin, and "
        "mowing time per day is short enough (see table) that a cloudy stretch just means a missed day. "
        "A **36 V 10–15 Ah pack** is enough as a buffer; no charging dock is needed. The battery "
        "charges while parked in the sun and the robot can mow mornings and evenings.",
        f"- **The Ryobi deck cannot be solar-powered** on this roof ({sg[0] + sg[2]:.0f}–{sg[1] + sg[3]:.0f} Wh/day); "
        "it needs the dock and a 20–40 Ah pack. It stays the catch-up tool for tall growth, pushed by hand.",
        "- **The razor regime only works if the robot keeps up**: razor blades shave a few millimetres of regrowth. "
        "After a missed week or in spring, mow once with the Ryobi (or the Swisher) first.",
        "",
        "**Measure in step 1:** one disc motor's current while cutting (expect 10–20 W on a maintained lawn), "
        "and the panel's actual midday output on the roof's horizontal mounting.",
    ]
    (OUT / "drive-energy-report.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
