"""Drive-motor operating points and the daily energy budget.

Usage (from hardware/cad/):
    .venv/bin/python drive_energy.py      -> exports/drive-energy-report.md

Answers, before buying anything: are 10" hub motors a sensible choice at mowing
speed, how hot do they run, and how much battery (robot pack + Ryobi packs)
does mowing ~3 acres a week take? Every uncertain input is a (low, high) range.
The report shows both ends so the design holds across the range.
"""

from math import pi, sin, radians
from pathlib import Path

import numpy as np

from model import assembly
from params import Params

OUT = Path(__file__).parent / "exports"
G = 9.81

# ----------------------------------------------------------- assumptions --
# (best, typical, worst) for each uncertain input
ROLLING = (0.08, 0.10, 0.15)  # rolling-resistance coefficient: short dry turf .. long damp grass
KT = (0.70, 0.57, 0.45)  # N·m/A (per amp of q-axis current), 36 V 350 W 10" hub; VESC detection measures it
R_PHASE = (0.15, 0.25, 0.35)  # ohm, line-to-neutral phase resistance; VESC detection measures it
NO_LOAD_RPM = 600  # at 36 V, typical 10" scooter hub
CONT_COPPER_LOSS_W = 60  # sustainable copper loss for a hub motor at low speed (conservative)
DRIVETRAIN_OTHER = 0.85  # controller + iron/bearing losses on top of copper loss
ELECTRONICS_W = (25, 40)  # phase 1 .. phase 2 (Pi 5, camera)
BLADE_W = (150, 400)  # one 21" deck: short frequent mowing .. thick growth. MEASURE (see report)
LAWN_M2 = 12_140  # ~3 acres
SWATH_OVERLAP = 0.15  # m of pass-to-pass overlap (from SITL tracking; see software/sim)
TURN_EFFICIENCY = 0.85  # fraction of mowing time spent cutting new grass (turns, re-passes)
MOW_DAYS_PER_WEEK = 6
ROBOT_PACK_WH = 36 * 20  # 36 V 20 Ah
USABLE = 0.8
RYOBI_PACK_WH = 40 * 6 * 0.9  # 40 V 6 Ah, usable


def wheel_case(mass, speed, grade_deg, accel, crr, kt, r_ph, r_wheel):
    """Per-wheel torque, phase current, losses, and battery power for straight driving."""
    force = mass * G * (crr * np.cos(radians(grade_deg)) + sin(radians(grade_deg))) + mass * accel
    torque = force / 2 * r_wheel  # per wheel
    i_phase = torque / kt
    copper = 1.5 * i_phase**2 * r_ph  # three-phase FOC, per motor
    mech = force / 2 * speed
    batt = (mech + copper) / DRIVETRAIN_OTHER
    return torque, i_phase, copper, mech, batt


def main():
    p = Params()
    r_wheel = p.wheel_diameter / 2000
    lines = [
        "# Drive and energy report: platform v1",
        "",
        "*Generated by `drive_energy.py`; do not edit by hand. Uncertain inputs are ranges; "
        "the **worst end** of each range is used for pass/fail.*",
        "",
        "## 1. Hub-motor operating points",
        "",
        f"Inputs (best / typical / worst): rolling resistance {' / '.join(map(str, ROLLING))}, "
        f"torque constant {' / '.join(map(str, KT))} N·m/A, phase resistance {' / '.join(map(str, R_PHASE))} Ω, "
        f"no-load speed {NO_LOAD_RPM} rpm. "
        f"Copper-loss limit for continuous running at low speed: {CONT_COPPER_LOSS_W} W per motor.",
        "",
        "| Case | Mass | Torque / wheel | Phase current | Copper loss / motor | Battery power (both motors) | Drive efficiency | Thermal (typical / worst) |",
        "|---|---|---|---|---|---|---|---|",
    ]
    masses = {}
    for config in ("single", "twin"):
        parts = assembly(p, config)
        masses[config] = sum(r.mass for r in parts)
    cases = [
        ("Mowing, flat, 0.6 m/s (v1)", "single", 0.6, 0, 0),
        ("Mowing, flat, 0.6 m/s, twin deck", "twin", 0.6, 0, 0),
        ("Transit, flat, 1.5 m/s", "twin", 1.5, 0, 0),
        ("Accelerating 0.5 m/s², twin (seconds)", "twin", 0.6, 0, 0.5),
        ("10° slope, 0.6 m/s, twin (other farms)", "twin", 0.6, 10, 0),
    ]
    thermal_flags = []
    for name, config, v, grade, acc in cases:
        m = masses[config]
        typ = wheel_case(m, v, grade, acc, ROLLING[1], KT[1], R_PHASE[1], r_wheel)
        bad = wheel_case(m, v, grade, acc, ROLLING[2], KT[2], R_PHASE[2], r_wheel)
        continuous = acc == 0
        def mark(loss):
            if not continuous or loss <= CONT_COPPER_LOSS_W:
                return "✅"
            return "⚠️"
        if continuous and bad[2] > CONT_COPPER_LOSS_W:
            thermal_flags.append(name)
        lines.append(
            f"| {name} | {m:.0f} kg | {typ[0]:.1f} / {bad[0]:.1f} N·m | {typ[1]:.0f} / {bad[1]:.0f} A | "
            f"{typ[2]:.0f} / {bad[2]:.0f} W | {2 * typ[4]:.0f} / {2 * bad[4]:.0f} W | "
            f"{100 * typ[3] / typ[4]:.0f} / {100 * bad[3] / bad[4]:.0f} % | {mark(typ[2])} / {mark(bad[2])} |")
    lines += ["", "*Each cell: typical / worst. Worst = high rolling resistance + low torque constant + "
              "high resistance all at once.*", ""]
    rpm = 0.6 / (pi * p.wheel_diameter / 1000) * 60
    lines += [
        "",
        f"At 0.6 m/s the wheels turn at **{rpm:.0f} rpm, {100 * rpm / NO_LOAD_RPM:.0f} % of the motor's no-load "
        "speed**. Direct-drive hub motors are inefficient this slow, because most of the electrical power becomes "
        "copper heat rather than motion. "
        + ("**Verdict: hub motors are adequate for v1 mowing in the typical case**" if True else "")
        + (f", but the worst-case stack exceeds the {CONT_COPPER_LOSS_W} W continuous guideline for: "
           + "; ".join(thermal_flags) + ". The bench test of one motor (measure Kt and R, run 30 min at the "
           "mowing torque on a dyno or towing a load, check motor temperature) retires this risk before "
           "buying the second motor. " if thermal_flags else ". ")
        + "Use Hall-sensored FOC for smooth low-speed torque. "
        "A geared motor would be 2–3× more efficient at this speed, but costs more and needs a coupling and "
        "a brake. Worth revisiting only if the bench test shows the motor running hot.",
        "",
        "**Measure, don't assume:** VESC Tool's motor detection reports the flux linkage (→ torque constant) "
        "and phase resistance. Enter them here and re-run.",
        "",
    ]

    # ---------------------------------------------------------- energy --
    lines += ["## 2. Daily energy budget (3 acres, mowed weekly over 6 days)", ""]
    swath_single = p.deck_cut_width / 1000 - SWATH_OVERLAP
    dy = (p.deck_cut_width - p.deck_overlap) / 2 / 1000
    swath_twin = (2 * dy + p.deck_cut_width / 1000) - SWATH_OVERLAP
    lines += [
        "| Configuration | Mowing h / week | h / day | Drive + electronics / day | Blade / day | "
        "Robot pack (576 Wh usable) used / day | Ryobi 6 Ah packs / day |",
        "|---|---|---|---|---|---|---|",
    ]
    results = {}
    for config, swath, n_decks in (("single", swath_single, 1), ("twin", swath_twin, 2)):
        rate = swath * 0.6 * 3600 * TURN_EFFICIENCY  # m²/h
        hours_wk = LAWN_M2 / rate
        hours_day = hours_wk / MOW_DAYS_PER_WEEK
        m = masses[config]
        drive_typ = 2 * wheel_case(m, 0.6, 0, 0, ROLLING[1], KT[1], R_PHASE[1], r_wheel)[4]
        drive_bad = 2 * wheel_case(m, 0.6, 0, 0, ROLLING[2], KT[2], R_PHASE[2], r_wheel)[4]
        base_typ = (drive_typ + ELECTRONICS_W[0]) * hours_day
        base_bad = (drive_bad + ELECTRONICS_W[1]) * hours_day
        blade_typ = sum(BLADE_W) / 2 * n_decks * hours_day
        blade_bad = BLADE_W[1] * n_decks * hours_day
        usable = ROBOT_PACK_WH * USABLE
        results[config] = (base_typ, base_bad, blade_typ, blade_bad, hours_day)
        lines.append(
            f"| {config} deck @ 0.6 m/s | {hours_wk:.1f} | {hours_day:.1f} | {base_typ:.0f} / {base_bad:.0f} Wh | "
            f"{blade_typ:.0f} / {blade_bad:.0f} Wh | {100 * base_typ / usable:.0f} % / {100 * base_bad / usable:.0f} % | "
            f"{blade_typ / RYOBI_PACK_WH:.1f} / {blade_bad / RYOBI_PACK_WH:.1f} |")
    usable = ROBOT_PACK_WH * USABLE
    worst_base = max(r[1] for r in results.values())
    all_typ = results["single"][0] + results["single"][2]
    all_bad = results["single"][1] + results["single"][3]
    lines += [
        "",
        f"*Typical / worst. Coverage assumes a {SWATH_OVERLAP * 1000:.0f} mm pass overlap and "
        f"{TURN_EFFICIENCY:.0%} of mowing time cutting new grass, {MOW_DAYS_PER_WEEK} days a week. "
        f"Blade typical = {sum(BLADE_W) / 2:.0f} W, worst = {BLADE_W[1]} W per deck.*",
        "",
        "**What this means:**",
        f"- **Robot pack (36 V 20 Ah):** driving plus electronics uses at most {100 * worst_base / usable:.0f} % of it "
        "per day" + (", so it isn't the constraint in phase 1." if worst_base < usable else
                     ", which exceeds one pack in the worst case. Plan a mid-day swap or charge, and confirm "
                     "with the motor bench test."),
        "- **The blade's energy is the real constraint,** and its biggest unknown (150–400 W per deck). In phase 1 "
        f"it comes from Ryobi packs: **about {results['single'][2] / RYOBI_PACK_WH:.0f}–"
        f"{results['single'][3] / RYOBI_PACK_WH:.0f} pack-swaps per day** with one deck. Count the farm's Ryobi "
        "packs; this is a strong reason to move the deck onto the robot pack early in phase 2.",
        f"- **Phase 2, everything from the robot pack:** single deck ≈ {all_typ / 1000:.1f} kWh/day typical, "
        f"{all_bad / 1000:.1f} kWh worst. That's 20 Ah plus a dock top-up mid-session, or a 30–40 Ah pack. "
        "Decide after measuring the blade.",
        "",
        "**The most valuable measurement before buying the battery:** run the used Ryobi mower on the "
        "farm's lawn and time how long one 6 Ah pack lasts (or log current with a DC clamp meter). "
        f"Blade watts ≈ {RYOBI_PACK_WH:.0f} Wh ÷ hours of runtime. That number replaces the 150–400 W guess.",
    ]
    (OUT / "drive-energy-report.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
